disabled = false
locale = "en"
label = "English"
weight = 1
title = "Jarrod J Scott"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "DESCRIPTION This is in languages.en.toml"
  logo = "logo.png"

[params.author]
  name = "Jarrod J Scott"
  email = "jarrod.jukebox308@slmail.me"
  image = "images/cover.jpg"
  banner = "images/mind_map.jpg"
  imageQuality = 96
  headline = "Field biologist, systems ecologist, data scientist, interdisciplinary researcher."
  bio = "My approach to biological questions is interdisciplinary & systems oriented. I combine field ecology, molecular & computational methods, ecological statistics, & advanced visualization to investigate how organisms coalesce into communities & how complex community interactions shape the structure & function of systems."
  full_bio_url = "research-portfolio/bio/"
  interests = [
  "Symbiosis",
  "Complexity",
  "DNA",
  "Ethnobotany",
  "'Omics",
  "Coevolution"
]
  skills = [ "Field", "Lab", "'Omics", "R", "Python", "Quarto", "Workflows", "Graphics"]

    [[params.author.links]]
    google-scholar = "https://scholar.google.com/citations?hl=en&user=5qejxxIAAAAJ"

    [[params.author.links]]
    github = "https://github.com/jarrodscott"

    [[params.author.links]]
    orcid = "https://orcid.org/0000-0001-9863-1318"

    [[params.author.links]]
    researchgate = "https://www.researchgate.net/profile/Jarrod-Scott-3"

    [[params.author.links]]
    email = "mailto:jarrod.jukebox308@slmail.me"

    [[params.author.links]]
    envelope = "/contact"

    [[params.author.education]]
    course = "PhD Microbiology"
    institution = "University of Wisconsin-Madison"
    year = "2011"

    [[params.author.education]]
    course = "BSc Biology"
    institution = "University of Texas-Austin"
    year = "2002"

    [[params.author.aboutButtons]]
    text = "Experience & Training"
    url = "/research-portfolio/experience/"
    icon = "graduation-cap"

    [[params.author.aboutButtons]]
    text = "Publications"
    url = "/research-portfolio/featured-publications/"
    icon = "pdf"

    [[params.author.aboutButtons]]
    text = "Expertise"
    url = "/research-portfolio/expertise/"
    icon = "microscope"

    [[params.author.aboutButtons]]
    text = "Products"
    url = "/research-portfolio/products/"
    icon = "chalkboard"

    [[params.author.aboutButtons]]
    text = "Media"
    url = "/research-portfolio/media/"
    icon = "newspaper"
