disabled = false
locale = "en"
label = "English"
weight = 1
title = ""

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "DESCRIPTION This is in languages.en.toml"
  logo = "images/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Jarrod J Scott"
  email = "jarrod.jukebox308@slmail.me"
  image = "images/cover.png"
  imageQuality = 96
  #headline = "Field biologist, systems ecologist, data scientist, interdisciplinary researcher."
  #bio = "My approach to biological questions is interdisciplinary & systems oriented. I combine field ecology, molecular & computational methods, ecological statistics, & advanced visualization to investigate how organisms coalesce into communities & how complex community interactions shape the structure & function of systems."
#  links = [
#    { google-scholar = "https://scholar.google.com/citations?hl=en&user=5qejxxIAAAAJ" },
#    { github = "https://github.com/jarrodscott" },
#    { orcid = "https://orcid.org/0000-0001-9863-1318" },
#    { researchgate = "https://www.researchgate.net/profile/Jarrod-Scott-3" }
#  ]
