# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
  unsafe = true
  [goldmark.parser]
    [goldmark.parser.attribute]
      block = true  # Allows attributes below markdown blocks

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 2
  endLevel = 4
  
# I added this section below
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']] # Added '$' delimiters

[params]
  math = true 

  