colorScheme = "default"
defaultAppearance = "light"
autoSwitchAppearance = false
enableA11y = true
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = true
replyByEmail = false
mainSections = [ "study" ]
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
defaultBackgroundImage = "images/v3/site-background.svg"
backgroundCanvas = false
defaultFeaturedImage = "/img/featured.svg"
defaultSocialImage = "/img/blowfish_banner.png"
hotlinkFeatureImage = false
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false
fingerprintAlgorithm = "sha512"
firebase = { }
fathomAnalytics = { }
umamiAnalytics = { }
selineAnalytics = { }
buymeacoffee = { }
verification = { }
rssnext = { }
advertisement = { }

[header]
layout = "floating"
mobileMenuStyle = "dropdown"
theme_picker = true

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "custom"
layoutSwitcher = false
homepageImage = "images/bretz_map.png"
showRecent = false
showRecentItems = 4
showMoreLink = false
showMoreLinkDest = "/research-portfolio"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = true
disableHeroImageFilter = false

[article]
showDate = false
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = false
heroStyle = "basic"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = true
editURL = "https://github.com/jarrodscott/jarrodscott.github.io/tree/main/content"
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showReadingProgress = true
showTableOfContents = true
showRelatedContent = false
relatedContentLimit = 9
showTaxonomies = false
showAuthorsBadges = false
showWordCount = true
showZenMode = false
showCategories = true
showTags = true
showCategoriesInSecondaryColor = false
#sharingLinks = [ "linkedin", "twitter", "bluesky", "reddit", "whatsapp", "telegram", "pinterest", "facebook", "email", "line"]

[list]
showHero = false
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = true
showSummary = true
showViews = false
showLikes = false
showTableOfContents = true
showCards = true
orderByWeight = false
groupByYear = false
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false
featureImageHover = true

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
heroStyle = "background"
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true

[term]
showHero = false
heroStyle = "background"
showBreadcrumbs = true
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true

[languageRedirect]
enabled = false
storageKey = "blowfish_preferred_language"
browserRedirectHomeOnly = true
storedLanguageRedirect = true
